// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrmRs-XQgFPzcf5CFvYcRqf0b3oj9oG0',
    appId: '1:594713199077:web:0b528ed5fc6ccd727baf0c',
    messagingSenderId: '594713199077',
    projectId: 'acadmian-526a7',
    authDomain: 'acadmian-526a7.firebaseapp.com',
    storageBucket: 'acadmian-526a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkv_saucoLq3qIQ_dYJhG3hbWTL7YJaE',
    appId: '1:594713199077:android:237cf5f890a32a8b7baf0c',
    messagingSenderId: '594713199077',
    projectId: 'acadmian-526a7',
    storageBucket: 'acadmian-526a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwwsGUrRK1KZVXe9Rwb9846gNgQ2C46M',
    appId: '1:594713199077:ios:2135b681d6b909db7baf0c',
    messagingSenderId: '594713199077',
    projectId: 'acadmian-526a7',
    storageBucket: 'acadmian-526a7.appspot.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwwsGUrRK1KZVXe9Rwb9846gNgQ2C46M',
    appId: '1:594713199077:ios:2135b681d6b909db7baf0c',
    messagingSenderId: '594713199077',
    projectId: 'acadmian-526a7',
    storageBucket: 'acadmian-526a7.appspot.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQrmRs-XQgFPzcf5CFvYcRqf0b3oj9oG0',
    appId: '1:594713199077:web:a35bf380c708fe1f7baf0c',
    messagingSenderId: '594713199077',
    projectId: 'acadmian-526a7',
    authDomain: 'acadmian-526a7.firebaseapp.com',
    storageBucket: 'acadmian-526a7.appspot.com',
  );
}
